language: lisp
sudo: required

branches:
  only:
    - master

env:
  matrix:
    - LISP=sbcl
    - LISP=abcl
    - LISP=ccl
    - LISP=clisp

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh

script:
  - cl -e "(ql:quickload :aws-sign4) (asdf:test-system :aws-sign4)"
